### ISSUE TITLE
Did you test the code in Ubuntu OS?

### ISSUE THREAD

**Issue by faisalmozher** [antonypro/AudioStreaming#2]
Hi, I just tried to run your project in a Ubuntu system, but in the client side it always complains saying "Got a buffer underflow!". Have you faced this problem yet?

Thanks.

**Comment by antonypro** [comment]
I launched a new version that includes an optional buffer, tested on windows, linux and Mac OS, this should reduce the problem because makes the output audio consume the buffer when something happens in network and gives the chance to Server restore from their problem without buffer underrun. The penalty for this is increase the latency which should be a problem for realtime applications.

Please try it!
